version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: parking_postgres
    restart: always
    environment:
      POSTGRES_DB: parkingdb
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parking_net

volumes:
  postgres_data:

networks:
  parking_net:
    driver: bridge
